### ISSUE TITLE
Windows cannot check out.

### ISSUE THREAD

**Issue by CarnageMarkus** [tominabox1/_33-Keyboard#5]
Git for windows has trouble checking out Rev2 as the folder has space at the end.
![screen](https://user-images.githubusercontent.com/9625437/148192017-a573aa75-c040-4231-be27-1110f87430ae.png)

**Comment by tominabox1** [comment]
Thanks for the heads up! I have pushed an update to fix this, please try again!

**Comment by CarnageMarkus** [comment]
Works. Thanks a lot!
